document.addEventListener('DOMContentLoaded',()=>{
const themeSwitch=document.getElementById('themeSwitch');
const applyTheme=(theme, persist=true)=>{const dark=theme==='dark';document.documentElement.dataset.theme=dark?'dark':'light';if(themeSwitch){themeSwitch.querySelector('span').textContent=dark?'☾':'☼';themeSwitch.setAttribute('aria-label',dark?'Tukar ke tema siang':'Tukar ke tema malam');themeSwitch.title=dark?'Tukar ke Light Mode':'Tukar ke Dark Mode';}if(persist){try{localStorage.setItem('project3-theme',theme);}catch(e){}}};
let savedTheme='light';try{savedTheme=localStorage.getItem('project3-theme')||'light';}catch(e){}
const requestedTheme=new URLSearchParams(window.location.search).get('theme');
applyTheme(requestedTheme==='dark'||requestedTheme==='light'?requestedTheme:savedTheme, Boolean(requestedTheme));
if(themeSwitch) themeSwitch.addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
const links=document.querySelectorAll('.side-link'),sections=document.querySelectorAll('.dash-section');links.forEach(link=>link.addEventListener('click',()=>{links.forEach(x=>x.classList.remove('active'));link.classList.add('active');sections.forEach(s=>s.classList.toggle('active-section',s.id===link.dataset.target));window.scrollTo({top:0,behavior:'smooth'});}));
const day=document.getElementById('day'),clock=document.getElementById('clock');const tick=()=>{const d=new Date();const lang=window.P3_LANG||'ms';const locale=lang==='en'?'en-MY':lang==='id'?'id-ID':'ms-MY';day.textContent=d.toLocaleDateString(locale,{weekday:'long',day:'numeric',month:'long',year:'numeric'});clock.textContent=d.toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit'});};tick();setInterval(tick,1000);document.addEventListener('p3LanguageChanged',tick);
const skillData={HTML:{ms:'HTML membina struktur asas halaman web. Saya sedang mengukuhkan penggunaan semantic elements dan struktur halaman yang kemas.',en:'HTML builds the basic structure of web pages. I am strengthening my use of semantic elements and clean page structure.',id:'HTML membina struktur asas halaman web. Saya sedang mengukuhkan penggunaan elemen semantik dan struktur halaman yang kemas.'},CSS:{ms:'CSS digunakan untuk menghasilkan layout, tipografi, warna, spacing dan responsive design.',en:'CSS is used for layout, typography, colour, spacing and responsive design.',id:'CSS digunakan untuk menghasilkan susun atur, tipografi, warna, jarak dan reka bentuk responsif.'},JavaScript:{ms:'JavaScript membantu saya menghasilkan interaksi seperti popup, button, navigation dan perubahan kandungan.',en:'JavaScript helps me create interactions such as popups, buttons, navigation and content changes.',id:'JavaScript membantu saya menghasilkan interaksi seperti popup, butang, navigasi dan perubahan kandungan.'},Networking:{ms:'Networking membantu saya memahami sambungan peranti, konfigurasi asas dan simulasi rangkaian menggunakan Cisco Packet Tracer.',en:'Networking helps me understand device connections, basic configuration and network simulation using Cisco Packet Tracer.',id:'Networking membantu saya memahami sambungan peranti, konfigurasi asas dan simulasi rangkaian menggunakan Cisco Packet Tracer.'}};
const skillModal=document.getElementById('skillModal'),skillTitle=document.getElementById('skillTitle'),skillText=document.getElementById('skillText');document.querySelectorAll('.skill-card').forEach(card=>card.addEventListener('click',()=>{const name=card.dataset.skill;skillTitle.textContent=name;const lang=window.P3_LANG||'ms';skillText.textContent=(skillData[name]&&skillData[name][lang])||skillData[name]?.ms||'Kemahiran yang sedang saya pelajari dan kembangkan.';skillModal.classList.add('open');skillModal.setAttribute('aria-hidden','false');}));document.getElementById('closeSkill').addEventListener('click',()=>{skillModal.classList.remove('open');skillModal.setAttribute('aria-hidden','true');});
const toolModal=document.getElementById('toolModal'),toolTitle=document.getElementById('toolTitle'),toolText=document.getElementById('toolText');const toolInfo={'VS Code':{ms:'Digunakan untuk menulis, menyusun dan menguji fail HTML, CSS dan JavaScript.',en:'Used to write, organise and test HTML, CSS and JavaScript files.',id:'Digunakan untuk menulis, menyusun dan menguji fail HTML, CSS dan JavaScript.'},'Canva':{ms:'Digunakan untuk menghasilkan bahan grafik dan multimedia.',en:'Used to create graphic and multimedia materials.',id:'Digunakan untuk menghasilkan bahan grafik dan multimedia.'},'Cisco Packet Tracer':{ms:'Digunakan untuk simulasi rangkaian dan latihan konfigurasi peranti.',en:'Used for network simulation and device configuration practice.',id:'Digunakan untuk simulasi rangkaian dan latihan konfigurasi peranti.'},'Chrome':{ms:'Digunakan untuk melihat, menguji dan menyemak fungsi laman web.',en:'Used to view, test and check website functions.',id:'Digunakan untuk melihat, menguji dan menyemak fungsi laman web.'}};document.querySelectorAll('.tools button').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.tool;toolTitle.textContent=n;const lang=window.P3_LANG||'ms';toolText.textContent=toolInfo[n]?.[lang]||toolInfo[n]?.ms||'';toolModal.classList.add('open');toolModal.setAttribute('aria-hidden','false');}));document.getElementById('closeTool').addEventListener('click',()=>{toolModal.classList.remove('open');toolModal.setAttribute('aria-hidden','true');});
[skillModal,toolModal].forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){skillModal.classList.remove('open');toolModal.classList.remove('open');}});
document.querySelectorAll('.focus-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.focus-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');}));document.querySelectorAll('.focus-panel input').forEach(input=>input.addEventListener('change',()=>{input.parentElement.classList.toggle('done',input.checked);}));const goalBtn=document.getElementById('goalBtn');goalBtn.addEventListener('click',()=>{document.getElementById('goalMsg').textContent='✓ Goal saved — keep learning and keep building!';goalBtn.textContent=(window.P3_LANG==='en'?'GOAL SAVED ✓':window.P3_LANG==='id'?'TUJUAN TERSIMPAN ✓':'MATLAMAT DISIMPAN ✓');});});